version: '3.7'

services:
  pro-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - env=local
    ports:
      - "8085:8085"
    env_file:
      - .env
    command:
      - "-host="
      - "-production=false"
    restart: unless-stopped