defaultEntryPoints = ["http", "https"]
logLevel = "INFO"

[docker]
    endpoint = "unix:///var/run/docker.sock"
    exposedByDefault = true

[api]
    entrypoint = "traefik"
    dashboard = true

# Force HTTPS
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[file]
  watch = true
  filename = "/etc/traefik/traefik.toml"

domain = "docker.localhost"
swarmMode = true