name: gopro build/test flow
on:
  push:
    branches:
      - master

# 1. Test local code
# 1a. Clone it to company repo
# 2. Build docker image img:tag
# 3. Push docker image img:tag to docker hub
# 4. SSH into linux server
# 5. copy/paste/replace local docker-compose.yml on linux server (it's gitignored)
# 6. inside server > Docker pull img:tag
# 7. docker-compose up -d

jobs:
  review:
    name: review and build code
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@master ?
      - name: Checkout to master
        uses: actions/checkout@master

      - name: Set up go v1.13
        uses: actions/setup-go@v1
        with:
          go-version: "1.13" # The Go version to download (if necessary) and use.
        id: go

      - name: Go version
        run: go version

      - name: Go test
        run: go test ./...

      - name: Go vet
        run: go vet

      - name: docker login
        uses: actions/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: docker build img
        uses: actions/docker/cli@master
        with:
          args: build --rm -f "Dockerfile" -t byrdapp/gopro .

      - name: docker push
        uses: actions/docker/cli@master
        with:
          args: push byrdapp/gopro

    # test:
    #   needs: build
    # deploy_to_do:
    #   needs: [build, test]
    # copy_to_byrd:
    #   needs: [build, test]
