name: Gopro
on:
  push:
    branches:
      - master

# jobs:
#   build-dev:
#     name: Build the API
#     runs-on: ubuntu-latest
#     steps:
#       - name: Build app as Go 1.12
#         # uses: actions/setup-go@v1
#         with:
#           go-version: 1.12
#         id: go

#         # env:
#         # ENV: development
#         # POSTGRES: ${{ secrets.POSTGRES }}
#       - name: Check out code into the Go module directory
#         uses: actions/checkout@v1

#       - name: Get dependencies
#         run: |
#           go get -v -t -d ./...
#           if [ -f go.mod ]; then
#               curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
#               dep ensure
#           fi

#       - name: Build
#         run: go build -v .
#   # test:
#   #   needs: build
#   # deploy_to_do:
#   #   needs: [build, test]
#   # copy_to_byrd:
#   #   needs: [build, test]
